"""Initial migration.

Revision ID: 29a2a6be3b90
Revises: fdfe7802d038
Create Date: 2021-11-01 21:09:30.535659

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = '29a2a6be3b90'
down_revision = 'fdfe7802d038'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('namefilm', sa.String(length=45), nullable=True),
    sa.Column('datatime', mysql.DATETIME(), nullable=True),
    sa.Column('reservation', sa.String(length=45), nullable=True),
    sa.Column('buy', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=45), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('idticket', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idticket'], ['Tickets.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Buy')
    op.drop_table('User')
    op.drop_table('Tickets')
    # ### end Alembic commands ###
