"""Initial migration.

Revision ID: 5505c5a8f0a1
Revises: 
Create Date: 2021-11-25 14:58:02.818568

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '5505c5a8f0a1'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('User',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=False),
    sa.Column('username', sa.String(length=45), nullable=True),
    sa.Column('password', sa.String(length=70), nullable=True),
    sa.Column('rang', sa.String(length=70), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('token_block_list',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('jti', sa.String(length=36), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Tickets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('row', sa.Integer(), nullable=True),
    sa.Column('place', sa.Integer(), nullable=True),
    sa.Column('namefilm', sa.String(length=45), nullable=True),
    sa.Column('datatime', sa.DATETIME(), nullable=True),
    sa.Column('reservation', sa.String(length=45), nullable=True),
    sa.Column('buy', sa.String(length=45), nullable=True),
    sa.Column('id_user_create', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['id_user_create'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('Buy',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=45), nullable=True),
    sa.Column('idticket', sa.Integer(), nullable=True),
    sa.Column('iduser', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['idticket'], ['Tickets.id'], ),
    sa.ForeignKeyConstraint(['iduser'], ['User.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Buy')
    op.drop_table('Tickets')
    op.drop_table('token_block_list')
    op.drop_table('User')
    # ### end Alembic commands ###
