"""Initial migration.

Revision ID: fdfe7802d038
Revises: 3ceabb1ac2ac
Create Date: 2021-11-01 19:15:39.911868

"""
from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import mysql

# revision identifiers, used by Alembic.
revision = 'fdfe7802d038'
down_revision = '3ceabb1ac2ac'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Gravity',
    sa.Column('GravityId', sa.Integer(), nullable=False),
    sa.Column('FvId', sa.Integer(), nullable=False),
    sa.Column('Gravity', sa.Float(), nullable=False),
    sa.Column('Timestamp', mysql.DATETIME(fsp=6), nullable=False),
    sa.ForeignKeyConstraint(['FvId'], ['Fv.FvId'], ),
    sa.PrimaryKeyConstraint('GravityId')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('Gravity')
    # ### end Alembic commands ###
